import os
import argparse
import pickle

import numpy as np
from pathlib import Path

from units import *

def generate_par(par_filename, parameters, planet, satellite):

    print('Making cdi parameter file -> {}'.format(par_filename))

    # writing to actual par file
    with open(par_filename, 'w') as f:
        f.write('#### THIS FILE IS AUTOGENERATED DO NOT EDIT BY HAND ####\n')
        for el in parameters.keys():
            f.write('{:32} {:64}'.format(el,str(parameters[el])).rstrip()+'\n')

    # pickle file to use parameters elsewhere in analysis code
    par_pickle_filename = 'cdi.par.pickle'
    with open(par_pickle_filename, 'wb') as f:
        pickle.dump(parameters, f)

# technically a satellite not a planet
def generate_satellite(satellite_filename, satellite):

    print('Making cdi planet file -> {}'.format(satellite_filename))

    # write to the planet file
    param_names = ['name', 'a', 'mass', 'accretion', 'feels_disk', 'feels_others']
    with open(satellite_filename, 'w') as f:
        f.write('#### THIS FILE IS AUTOGENERATED DO NOT EDIT BY HAND ####\n')
        for key in param_names:
            f.write(str(satellite[key])+' ')
        f.write('\n')

# gets the latest output directory
# useful so we don't accidentally overwrite old data
def get_outputdir():
    increment=0
    prepath = str(Path.home())
    outputdir = prepath+'/landing/data/cdi_'+str(increment).zfill(4)

    while os.path.isdir(outputdir):
        increment+=1
        outputdir = prepath+'/landing/data/cdi_'+str(increment).zfill(4)

    return outputdir
        
def main():

    planet = {}
    satellite = {}
    parameters = {}

    #####################
    # PLANET DEFINITION #
    #####################

    planet['mass'] = 1.0 * MJ_to_g # make sure MSTAR in fondham.h matches this

    ########################
    # SATELLITE DEFINITION #
    ########################

    satellite['name'] = 'CDIb'
    satellite['a'] = 0.1 * AU_to_cm
    #satellite['mass'] = 0.0001 *  MJ_to_g
    satellite['mass'] = 0.1 *  MJ_to_g
    satellite['period'] = 2*np.pi*np.sqrt(np.power(satellite['a'], 3)/(G_cgs*planet['mass']))
    satellite['accretion'] = 0.0
    satellite['feels_disk'] = 'YES'
    satellite['feels_others'] = 'YES'

    ########################
    # PARAMETER DEFINITION #
    ########################

    # wave damping
    parameters['DampingZone'] = 1.5
    parameters['TauDamp'] = 0.3

    # misc
    parameters['ExcludeHill'] = 'No' # hill sphere cutoff for force calculations
    parameters['IndirectTerm'] = 'Yes' # indirect term "ficticious force" due to gravity, usually set to yes

    # initial eccentricity of the planets
    parameters['Eccentricity'] = 0.0

    # rotating reference frame
    parameters['OmegaFrame'] = 0.0
    parameters['Frame'] = 'F'

    # smoothing parameters
    parameters['SigmaSlope'] = 0.8
    parameters['FlaringIndex'] = 0.25
    parameters['ThicknessSmoothing'] = 0.6
    parameters['RocheSmoothing'] = 0.0

    # disk parameters
    parameters['MassAccretion'] = 1.0e-7 * mass_accretion_conversion # jupiter mass / year to g / sec
    parameters['Alpha'] = 0.001

    # simulation files
    outputdir = get_outputdir()
    parameters['Setup'] = 'cdi'
    parameters['PlanetConfig'] = 'planets/cdi.cfg'
    parameters['OutputDir'] =  outputdir

    # boundaries
    r_t = 5*RJ_to_cm # truncation radius
    r_h = 5.2*AU_to_cm * np.power(planet['mass'] / (3*planet['mass']*1000), 1/3) # hill radius
    # x should be a full circle in units of radians
    parameters['Xmin'] = -np.pi
    parameters['Xmax'] = np.pi
    # inner/outer annulus distance
    parameters['Ymin'] = r_t
    parameters['Ymax'] = r_h

    # resolution parameters
    parameters['Spacing'] = 'log'
    grid_power = 7 # number of cells is 2^(n-1) , 2^n
    parameters['Ny'] = int(np.power(2, grid_power-1))
    parameters['Nx'] = int(np.power(2, grid_power))

    # timestep parameters
    parameters['DT'] = satellite['period']/10
    parameters['Ninterm'] = 1
    parameters['Ntot'] = 10

    # generate the par file
    par_filename = './cdi/cdi.par'
    generate_par(par_filename, parameters, planet, satellite)

    # generate satellite file
    satellite_filename = 'cdi.cfg'
    generate_satellite(satellite_filename, satellite)

if __name__=='__main__':
    main()
